[target.riscv32i-unknown-none-elf]
runner = "./run.sh"

rustflags = [
    # LLD (shipped with the Rust toolchain) is used as the default linker
    "-g",
    #"-C","link-arg=-Tmemory_asm.x",
    "-C","link-arg=-Tmemory.x",
    "-C","link-arg=-Tlink.x",
]

[build]
target = "riscv32i-unknown-none-elf"
